### ISSUE TITLE
Please change the faker value for 'Name' . $this->faker->randomNumber(); or $this->faker->bothify(' Code ?###?') 

### ISSUE THREAD

**Issue by nhungredweb** [NguyenTrang091296/Demo_Codeception#5]
https://github.com/NguyenTrang091296/Demo_Codeception/blob/add9e328511ae51d89c9f95c33e05024bc328987/tests/acceptance/Admin/ScheduleCest.php#L14

**Comment by NguyenTrang091296** [comment]
I change the fake value for 'Name' . $this->fake->numberBetween(). Please check again. Thanks @nhungredweb
